project:
  type: website
  output-dir: docs
  render:
   - "*.qmd"
   - "!pkg/"

website:
  site-url: "https:/https://dbetebenner.github.io/Quarto_Test"
  repo-url: "https://github.com/dbetebenner/Quarto_Test"
  title: "Quarto Test"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
     - sketchy
     - assets/custom.scss
    css: assets/styles.css
    toc: true
    include-after: |
      <link rel="stylesheet" href="/assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="/assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>
