project:
  type: website
  output-dir: docs
  render:
   - "*.qmd"
   - "!pkg/"

exectute:
  freeze: auto

website:
  site-url: "https://dbetebenner.github.io/Quarto_Test/"
  repo-url: "https://github.com/dbetebenner/Quarto_Test"
  title: "Effective Data Visualisation with R"
  repo-actions: [edit, issue]
  favicon: /assets/favicon.png

  # navigation
  page-navigation: true
  navbar:
    title: "Quarto Test"
    logo: assets/favicon.png
    logo-href: "https://centerforassessment.github.io/"
    search: false
    pinned: true
    left:
      - text: Documents
        href: documents.qmd
      - text: Presentations 
        href: presentations.qmd
      - text: News
        href: news.qmd
    right:
      - icon: github
        href: https://github.com/dbetebenner
      - icon: twitter
        href: https://twitter.com/dbetebenner

  search:
    location: navbar
    type: overlay
    copy-button: true

  #footer
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "LICENSE"
        href: LICENSE.qmd
      - text: "View source on Github"
        href: https://https://github.com/dbetebenner/Quarto_Test

  #socials
  open-graph: true
  twitter-card: 
    creator: "@dbetebenner"
    site: "@nciea1"

format:
  html:
    theme:
     - yeti
     - assets/custom.scss
    css: /assets/styles.css
    toc: true
    include-after: |
      <link rel="stylesheet" href="/assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="/assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>
