project:
  type: website
  output-dir: ../docs
  render:
   - "*.qmd"
   - "!pkg/"

execute:
  freeze: auto

website:
  site-url: "https://dbetebenner.github.io/Quarto_Test/"
  repo-url: "https://github.com/dbetebenner/Quarto_Test"
  title: "Effective Data Visualization with R"
  repo-actions: [edit, issue]
  favicon: ./assets/img/logo_color.png

  # navigation
  page-navigation: true
  navbar:
    title: "Quarto Test"
    logo: ./assets/img/logo_grey.png
    logo-href: "https://centerforassessment.github.io/"
    search: false
    pinned: true
    foreground: "#7c7c7c"
    right:
      - text: Documents
        href: documents.qmd
      - text: Presentations 
        href: presentations.qmd
      - text: News
        href: news.qmd
      - icon: github
        aria-label: github
        href: https://github.com/dbetebenner/Quarto_Test
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/dbetebenner

  search:
    location: navbar
    type: overlay
    copy-button: true

  #footer
  page-footer:
    center:
      - text: About
        href: about.qmd
      - icon: github
        text: GitHub
        aria-label: github
        href: https://https://github.com/dbetebenner/Quarto_Test

  #socials
  open-graph: true
  twitter-card: 
    creator: "@dbetebenner"
    site: "@nciea1"

format:
  html:
    theme:
     - cosmo
     - ./assets/css/custom.scss
    css: ./assets/css/styles.css
    toc: true
    include-after: |
      <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,600" rel="stylesheet" type="text/css">
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script type="text/javascript" src="/assets/js/jquery.sticky-kit.min.js"></script>
      <script type="text/javascript" src="/assets/js/scroll.js"></script>
